# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tito
tagline:             'The blog!'
description:         'This is the place where I would dump some of my ideas and some random things !'
url:                 http://taherio.github.io/
baseurl:             http://blog.azaby.com
#baseurl:            /
paginate:            5

# About/contact
author:
  name:              Tito
  url:               https://twitter.com/tito
  email:             test@test.com

# Custom vars
version:             1.0.0
